# Generated by Django 2.2.2 on 2019-06-23 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_blogpost_post_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ['comment_date']},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['post_date']},
        ),
        migrations.AddField(
            model_name='author',
            name='author_bio',
            field=models.TextField(default='too boring for a bio',
                                   verbose_name='AuthorBio'),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='comment_date',
            field=models.DateTimeField(auto_now=True,
                                       verbose_name='TimeOfPosting'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='comment_text',
            field=models.TextField(verbose_name='Commentfield'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_date',
            field=models.DateTimeField(auto_now=True,
                                       verbose_name='TimeOfPosting'),
        ),
    ]
